### PR TITLE
Get rid of warnings because of deprecated `#[deriving(x)]` constructs

### PR DESCRIPTION
**Pull request by akiss77**
Using new `#[derive(x)]` syntax.

### CODE REVIEW

**Comment by akiss77** [comment]
Travis fails now but will/should be OK as soon as https://github.com/Jurily/rust-xxhash/pull/13 lands.

**Comment by Jurily** [comment]
Thanks!

**Comment by akiss77** [comment]
Would it be possible to publish a new version to crates.io containing these changes? (Please also note that version is 0.0.4 here in the repo while already 0.0.5 in the published crate.)

**Comment by Jurily** [comment]
Done.

**Comment by akiss77** [comment]
Thanks!

**Pull request merged**
